apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timeserver
  template:
    metadata:
      labels:
        app: timeserver
    spec:
      containers:
        - name: timeserver
          image: myink/time_server:latest
          ports:
            - containerPort: 8080
        - name: timeserver-stats
          image: myink/statistics_script:latest

---

apiVersion: v1
kind: Service
metadata:
  name: timeserver
  labels:
    run: timeserver
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: timeserver
  type: NodePort
